#ifndef __DEFINITION_H__
#define __DEFINITION_H__

#define GRID_SIZE 32
#define PLAYER_WALK_FRAME 6
#define PLAYER_WALK_FRAMERATE 0.1
#define PLAYER_WALK_FRAME_TIME 0.01
#define PLAYER_WALK_SPEED_PER_FRAME_TIME 3

#define MAP_WIDTH 15
#define MAP_HEIGHT 10
#define TILES_WIDTH 22
#define TILES_HEIGHT 15

#define BUY 0
#define SELL 1

#endif // __DEFINITION_H__